apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todoapp-ingress
spec:
  rules:
  - http:
      paths:
      # Frontend
      - path: /todo
        pathType: Exact
        backend:
          service:
            name: todoapp-svc
            port:
              number: 2345