spring.application.name=todo_app
# Spring needs a port fallback value for app to start :(
server.port=${PORT:8081}
image.file.path=${IMAGE_FILE_PATH}
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE