spring.application.name=todo_app
server.port=${PORT:8080}
image.file.path=${IMAGE_FILE_PATH:/app/images/}
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE