apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: todoapp:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8081"
            - name: IMAGE_FILE_PATH
              value: /app/images/
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: todoapp-claim
              mountPath: /app
      volumes:
        - name: todoapp-claim
          persistentVolumeClaim:
            claimName: todoapp-claim