apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: project
data:
  POSTGRES_USER: dG9kby1iYWNrZW5k
  POSTGRES_PASSWORD: d2hhdHRvZG93aGF0dG9kbw==
  POSTGRES_DB: dG9kb2Ri
  POSTGRES_URL: amRiYzpwb3N0Z3Jlc3FsOi8vdG9kby1wc3FsLXN2Yzo1NDMyL3RvZG9kYg==