apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
      # Write service -----
        - name: write-service
          image: write-service:latest
          imagePullPolicy: IfNotPresent
          volumeMounts: # Mount volume
          - name: logoutput-claim
            mountPath: /shared
          env:
          - name: SHARED_FOLDER_PATH
            value: /shared/
      # Read service -----
        - name: read-service
          image: read-service:latest
          imagePullPolicy: IfNotPresent
          volumeMounts: # Mount volume
          - name: logoutput-claim
            mountPath: /shared
          - name: config-volume
            mountPath: /config
          env:
          - name: SHARED_FOLDER_PATH
            value: /shared/
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: log-output-config
                key: message.env
          
      # Volumes -----
      volumes:
        - name: logoutput-claim
          persistentVolumeClaim:
            claimName: logoutput-claim
        - name: config-volume
          configMap:
            name: log-output-config