apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: pingpong:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: logoutput-claim
            mountPath: /shared
          env:
          - name: SHARED_FOLDER_PATH
            value: /shared/
      volumes:
        - name: logoutput-claim
          persistentVolumeClaim:
            claimName: logoutput-claim