apiVersion: v1
kind: ConfigMap
metadata:
  name: pingpong-config
  namespace: exercises
data:
  POSTGRES_USER: "pingpong-app"
  POSTGRES_PASSWORD: "boing!"
  POSTGRES_DB: "pingpong"
  POSTGRES_URL: "jdbc:postgresql://psql-svc:5432/pingpong"